---
title: "bobtail_interactions_pilot"
author: "DEKERLE_Louis"
date: "2026-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r LIBRARIES}

library(igraph)

```

```{r DATA}

# First session
#adj_matrix = as.matrix(read.csv("interaction_matrix.csv", sep =";", header = FALSE)) #(not covered in the report)

# remove unidentified individuals 
#adj_matrix_ID = adj_matrix[-9,-9] # (not covered in the report)

# Second session
adj_matrix2 = as.matrix(read.csv("interaction_matrix2.csv", sep =";", header = FALSE))

# adj_matrix_all = adj_matrix_ID + adj_matrix2 # (not covered in the report)
```


```{r graph of interactions}

g <- make_empty_graph()

# create the graph
g <- graph_from_adjacency_matrix(
    adj_matrix2, # vector for the adjacency matrix 
    mode = c("undirected"), # our social network is undirected (interaction of A->B is the same as B->A)
    weighted = TRUE, # our social network is weighted (strength of association in pairs is weighted by the                          number of their interaction)
    diag = F, # we do not include the diagonal of the matrix as individuals do not interact with themselves
    add.colnames = NULL, #use the column names to name the vertices (nodes corresponding the the individuals)
    add.rownames = FALSE # do not use the raw names to name the vertices
)

# arrange the vertex in circle 
layout <-layout_in_circle(g)

# plot 
plot(g, layout = layout, main = "", edge.width = E(g)$weight*0.6)# E(g) containes the attributes of the edges such as the weight which is the number of interactions between the same pair of individuals. We multiply the weight by 0.6 to increase the contrast between the width of the lines.

```
```{r Structural properties}

#binary degrees # how many conspecifics does an individual interact with 
degree(g) # maximum binary degree for every individual => they all interact with each other at least once 

# densities 
edge_density(g, loops = FALSE) # existing edges / possible edges => they all interact with each other at least once 

#weighted degrees # total interactions
strength(
  g,
  vids = V(g), #The vertices for which the strength will be calculated
  loops = TRUE, #Logical; whether the loop edges are also counted. (here none)
  weights = NULL # use the default weight edge attribute in the matrix 
)

```

